//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV_MVC.WsConsulta {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListarProductos", Namespace="http://localhost.com/")]
    [System.SerializableAttribute()]
    public partial class ListarProductos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesUnidadesField;
        
        private int Inventario_MinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonedaField;
        
        private decimal precio_inField;
        
        private decimal precio_outField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DesProducto {
            get {
                return this.DesProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.DesProductoField, value) != true)) {
                    this.DesProductoField = value;
                    this.RaisePropertyChanged("DesProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DesUnidades {
            get {
                return this.DesUnidadesField;
            }
            set {
                if ((object.ReferenceEquals(this.DesUnidadesField, value) != true)) {
                    this.DesUnidadesField = value;
                    this.RaisePropertyChanged("DesUnidades");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Inventario_Min {
            get {
                return this.Inventario_MinField;
            }
            set {
                if ((this.Inventario_MinField.Equals(value) != true)) {
                    this.Inventario_MinField = value;
                    this.RaisePropertyChanged("Inventario_Min");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Moneda {
            get {
                return this.MonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.MonedaField, value) != true)) {
                    this.MonedaField = value;
                    this.RaisePropertyChanged("Moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal precio_in {
            get {
                return this.precio_inField;
            }
            set {
                if ((this.precio_inField.Equals(value) != true)) {
                    this.precio_inField = value;
                    this.RaisePropertyChanged("precio_in");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal precio_out {
            get {
                return this.precio_outField;
            }
            set {
                if ((this.precio_outField.Equals(value) != true)) {
                    this.precio_outField = value;
                    this.RaisePropertyChanged("precio_out");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost.com/", ConfigurationName="WsConsulta.wsSoap")]
    public interface wsSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetProductosResult del espacio de nombres http://localhost.com/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost.com/GetProductos", ReplyAction="*")]
        INV_MVC.WsConsulta.GetProductosResponse GetProductos(INV_MVC.WsConsulta.GetProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost.com/GetProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<INV_MVC.WsConsulta.GetProductosResponse> GetProductosAsync(INV_MVC.WsConsulta.GetProductosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductos", Namespace="http://localhost.com/", Order=0)]
        public INV_MVC.WsConsulta.GetProductosRequestBody Body;
        
        public GetProductosRequest() {
        }
        
        public GetProductosRequest(INV_MVC.WsConsulta.GetProductosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProductosRequestBody {
        
        public GetProductosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductosResponse", Namespace="http://localhost.com/", Order=0)]
        public INV_MVC.WsConsulta.GetProductosResponseBody Body;
        
        public GetProductosResponse() {
        }
        
        public GetProductosResponse(INV_MVC.WsConsulta.GetProductosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost.com/")]
    public partial class GetProductosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public INV_MVC.WsConsulta.ListarProductos[] GetProductosResult;
        
        public GetProductosResponseBody() {
        }
        
        public GetProductosResponseBody(INV_MVC.WsConsulta.ListarProductos[] GetProductosResult) {
            this.GetProductosResult = GetProductosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsSoapChannel : INV_MVC.WsConsulta.wsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsSoapClient : System.ServiceModel.ClientBase<INV_MVC.WsConsulta.wsSoap>, INV_MVC.WsConsulta.wsSoap {
        
        public wsSoapClient() {
        }
        
        public wsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INV_MVC.WsConsulta.GetProductosResponse INV_MVC.WsConsulta.wsSoap.GetProductos(INV_MVC.WsConsulta.GetProductosRequest request) {
            return base.Channel.GetProductos(request);
        }
        
        public INV_MVC.WsConsulta.ListarProductos[] GetProductos() {
            INV_MVC.WsConsulta.GetProductosRequest inValue = new INV_MVC.WsConsulta.GetProductosRequest();
            inValue.Body = new INV_MVC.WsConsulta.GetProductosRequestBody();
            INV_MVC.WsConsulta.GetProductosResponse retVal = ((INV_MVC.WsConsulta.wsSoap)(this)).GetProductos(inValue);
            return retVal.Body.GetProductosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<INV_MVC.WsConsulta.GetProductosResponse> INV_MVC.WsConsulta.wsSoap.GetProductosAsync(INV_MVC.WsConsulta.GetProductosRequest request) {
            return base.Channel.GetProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<INV_MVC.WsConsulta.GetProductosResponse> GetProductosAsync() {
            INV_MVC.WsConsulta.GetProductosRequest inValue = new INV_MVC.WsConsulta.GetProductosRequest();
            inValue.Body = new INV_MVC.WsConsulta.GetProductosRequestBody();
            return ((INV_MVC.WsConsulta.wsSoap)(this)).GetProductosAsync(inValue);
        }
    }
}
